/**
 * src/db/migrate.ts — programmatic wrapper around `scripts/db-migrate.js`.
 *
 * HISTORY: Pre-Sprint-E-Tier-1 this file called `drizzle-orm/better-sqlite3`'s
 * `migrate()`, which requires `drizzle/migrations/meta/_journal.json` —
 * generated by drizzle-kit. We hand-write our migration SQL (see
 * `scripts/db-migrate.js` file-level comment for the full rationale, tracked
 * as DRIFT-test3-015) so the meta directory doesn't exist, which means the
 * previous implementation would throw `ENOENT: meta/_journal.json` on any
 * invocation. The CTCI ingest audit during Sprint E surfaced the gap:
 * migration 0005 had landed in PR #26 but the local DB never picked it up
 * because the canonical runner (`pnpm db:migrate` → `scripts/db-migrate.js`)
 * was not run after merge, and any developer who invoked the programmatic
 * path (`tsx src/db/migrate.ts`) hit the drizzle-meta crash.
 *
 * FIX: This file now delegates to the same `scripts/db-migrate.js` that
 * `pnpm db:migrate` invokes. One path, one runner, one journal — no chance
 * of divergence between the two entrypoints. Idempotent: `db-migrate.js`
 * maintains its own `__migrations` table and is safe to re-run.
 *
 * Usage (unchanged from before):
 *   import { runMigrations } from './migrate';
 *   await runMigrations();
 *
 * Usage (CLI):
 *   pnpm tsx src/db/migrate.ts
 *   pnpm db:migrate                 ← canonical; same destination
 */

import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';

const SCRIPT_PATH = resolve(process.cwd(), 'scripts', 'db-migrate.js');

export function runMigrations(scriptPath: string = SCRIPT_PATH): void {
  console.log(`[migrate] Delegating to: ${scriptPath}`);
  const result = spawnSync(process.execPath, [scriptPath], {
    stdio: 'inherit',
    env: process.env,
  });
  if (result.error) {
    console.error('[migrate] FAILED to spawn runner');
    throw result.error;
  }
  if (typeof result.status === 'number' && result.status !== 0) {
    throw new Error(`db-migrate.js exited with status ${result.status}`);
  }
}

// CLI entrypoint — `pnpm tsx src/db/migrate.ts` or `node --import tsx src/db/migrate.ts`.
// `require.main === module` check is CommonJS; tsx in ESM mode uses import.meta.url.
const isDirectInvocation =
  typeof require !== 'undefined' && require.main === module;
const isESMDirectInvocation =
  typeof import.meta !== 'undefined' &&
  import.meta.url === `file://${process.argv[1]}`;

if (isDirectInvocation || isESMDirectInvocation) {
  try {
    runMigrations();
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}
